/******************************************************
 * ISA post behavior implementation file.             *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

//!Instruction lb post behavior method
void ac_post_behavior ( lb ){

};//!Instruction lbu post behavior method
void ac_post_behavior ( lbu ){

};//!Instruction lh post behavior method
void ac_post_behavior ( lh ){

};//!Instruction lhu post behavior method
void ac_post_behavior ( lhu ){

};//!Instruction lw post behavior method
void ac_post_behavior ( lw ){

};//!Instruction lwl post behavior method
void ac_post_behavior ( lwl ){

};//!Instruction lwr post behavior method
void ac_post_behavior ( lwr ){

};//!Instruction sb post behavior method
void ac_post_behavior ( sb ){

};//!Instruction sh post behavior method
void ac_post_behavior ( sh ){

};//!Instruction sw post behavior method
void ac_post_behavior ( sw ){

};//!Instruction swl post behavior method
void ac_post_behavior ( swl ){

};//!Instruction swr post behavior method
void ac_post_behavior ( swr ){

};//!Instruction addi post behavior method
void ac_post_behavior ( addi ){

};//!Instruction addiu post behavior method
void ac_post_behavior ( addiu ){

};//!Instruction slti post behavior method
void ac_post_behavior ( slti ){

};//!Instruction sltiu post behavior method
void ac_post_behavior ( sltiu ){

};//!Instruction andi post behavior method
void ac_post_behavior ( andi ){

};//!Instruction ori post behavior method
void ac_post_behavior ( ori ){

};//!Instruction xori post behavior method
void ac_post_behavior ( xori ){

};//!Instruction lui post behavior method
void ac_post_behavior ( lui ){

};//!Instruction add post behavior method
void ac_post_behavior ( add ){

};//!Instruction addu post behavior method
void ac_post_behavior ( addu ){

};//!Instruction sub post behavior method
void ac_post_behavior ( sub ){

};//!Instruction subu post behavior method
void ac_post_behavior ( subu ){

};//!Instruction slt post behavior method
void ac_post_behavior ( slt ){

};//!Instruction sltu post behavior method
void ac_post_behavior ( sltu ){

};//!Instruction instr_and post behavior method
void ac_post_behavior ( instr_and ){

};//!Instruction instr_or post behavior method
void ac_post_behavior ( instr_or ){

};//!Instruction instr_xor post behavior method
void ac_post_behavior ( instr_xor ){

};//!Instruction instr_nor post behavior method
void ac_post_behavior ( instr_nor ){

};//!Instruction nop post behavior method
void ac_post_behavior ( nop ){

};//!Instruction sll post behavior method
void ac_post_behavior ( sll ){

};//!Instruction srl post behavior method
void ac_post_behavior ( srl ){

};//!Instruction sra post behavior method
void ac_post_behavior ( sra ){

};//!Instruction sllv post behavior method
void ac_post_behavior ( sllv ){

};//!Instruction srlv post behavior method
void ac_post_behavior ( srlv ){

};//!Instruction srav post behavior method
void ac_post_behavior ( srav ){

};//!Instruction mult post behavior method
void ac_post_behavior ( mult ){

};//!Instruction multu post behavior method
void ac_post_behavior ( multu ){

};//!Instruction div post behavior method
void ac_post_behavior ( div ){

};//!Instruction divu post behavior method
void ac_post_behavior ( divu ){

};//!Instruction mfhi post behavior method
void ac_post_behavior ( mfhi ){

};//!Instruction mthi post behavior method
void ac_post_behavior ( mthi ){

};//!Instruction mflo post behavior method
void ac_post_behavior ( mflo ){

};//!Instruction mtlo post behavior method
void ac_post_behavior ( mtlo ){

};//!Instruction j post behavior method
void ac_post_behavior ( j ){

};//!Instruction jal post behavior method
void ac_post_behavior ( jal ){

};//!Instruction jr post behavior method
void ac_post_behavior ( jr ){

};//!Instruction jalr post behavior method
void ac_post_behavior ( jalr ){

};//!Instruction beq post behavior method
void ac_post_behavior ( beq ){

};//!Instruction bne post behavior method
void ac_post_behavior ( bne ){

};//!Instruction blez post behavior method
void ac_post_behavior ( blez ){

};//!Instruction bgtz post behavior method
void ac_post_behavior ( bgtz ){

};//!Instruction bltz post behavior method
void ac_post_behavior ( bltz ){

};//!Instruction bgez post behavior method
void ac_post_behavior ( bgez ){

};//!Instruction bltzal post behavior method
void ac_post_behavior ( bltzal ){

};//!Instruction bgezal post behavior method
void ac_post_behavior ( bgezal ){

};//!Instruction sys_call post behavior method
void ac_post_behavior ( sys_call ){

};//!Instruction instr_break post behavior method
void ac_post_behavior ( instr_break ){

};